# Generated by Django 2.2.25 on 2021-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpd', '0002_auto_20211209_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='manager',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
