# Generated by Django 2.2.25 on 2022-01-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpd', '0003_person_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='NTUser_ID',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='surname',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='manager',
        ),
        migrations.AddField(
            model_name='person',
            name='bonus_package',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '1/2'), (4, 'K2'), (5, '3'), (6, 'K3')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='end_user',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='person',
            name='mng_end_user',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[(1, 'active'), (2, ' deactivated ')], max_length=30, null=True),
        ),
    ]
