# Generated by Django 2.2.25 on 2022-01-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpd', '0005_auto_20220109_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[(1, 'active'), (2, ' deactivated ')], default=1, max_length=200, null=True),
        ),
    ]
