# Generated by Django 2.2.25 on 2022-01-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpd', '0006_auto_20220109_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bonus_package',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated')], max_length=200, null=True),
        ),
    ]
