# Generated by Django 2.2.25 on 2022-01-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpd', '0007_auto_20220111_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bonus_package',
        ),
    ]
