# Generated by Django 2.2.25 on 2022-01-11 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpd', '0008_remove_person_bonus_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_name', models.Field(default='', max_length=30)),
                ('individual_component_weight', models.Field(default='', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('team_component_weight', models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('CU_component_weight', models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('complementary_component_weight', models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='bonus_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='gpd.BonusPackage'),
        ),
    ]
